-- Esta función ya no es necesaria y ha sido eliminada.
-- La verificación de contraseñas ahora se realiza en la aplicación usando bcryptjs.
-- Este archivo se puede eliminar o mantener como histórico.
